---
version: 2
jobs:
   build-trusty:
     docker:
       - image: circleci/buildpack-deps:trusty-scm
     environment:
       - OCPN_TARGET:  trusty
     steps:
       - checkout
       - run: >
           echo "deb-src http://us.archive.ubuntu.com/ubuntu/ trusty main"
           | sudo tee -a /etc/apt/sources.list
       - run: >
           echo "deb-src http://us.archive.ubuntu.com/ubuntu/ trusty-updates main"
           | sudo tee -a /etc/apt/sources.list
       - run: cat /etc/apt/sources.list
       - run: ci/circleci-build-trusty.sh
       - run: ci/circleci-upload.sh
   build-xenial:
     docker:
       - image: circleci/buildpack-deps:xenial-scm
     environment:
       - OCPN_TARGET:  xenial
     steps:
       - checkout
       - run: >
           echo "deb-src http://us.archive.ubuntu.com/ubuntu/ xenial main"
           | sudo tee -a /etc/apt/sources.list
       - run: >
           echo "deb-src http://us.archive.ubuntu.com/ubuntu/ xenial-updates main"
           | sudo tee -a /etc/apt/sources.list
       - run: cat /etc/apt/sources.list
       - run: ci/circleci-build-debian.sh
       - run: ci/circleci-upload.sh
   build-bionic:
     docker:
       - image: circleci/buildpack-deps:bionic-scm
     environment:
       - OCPN_TARGET:  bionic
     steps:
       - checkout
       - run: >
           echo "deb-src http://us.archive.ubuntu.com/ubuntu/ bionic main"
           | sudo tee -a /etc/apt/sources.list
       - run: >
           echo "deb-src http://us.archive.ubuntu.com/ubuntu/ bionic-updates main"
           | sudo tee -a /etc/apt/sources.list
       - run: cat /etc/apt/sources.list
       - run: ci/circleci-build-debian.sh
       - run: ci/circleci-upload.sh
   build-focal:
     docker:
       - image: circleci/buildpack-deps:focal-scm
     environment:
       - OCPN_TARGET:  focal
     steps:
       - checkout
       - run: >
           echo "deb-src http://us.archive.ubuntu.com/ubuntu/ focal main"
           | sudo tee -a /etc/apt/sources.list
       - run: >
           echo "deb-src http://us.archive.ubuntu.com/ubuntu/ focal-updates main"
           | sudo tee -a /etc/apt/sources.list
       - run: cat /etc/apt/sources.list
       - run: ci/circleci-build-debian.sh
       - run: ci/circleci-upload.sh
   build-bionic-gtk3:
     docker:
       - image: circleci/buildpack-deps:bionic-scm
     environment:
       - BUILD_GTK3: 1
       - OCPN_TARGET:  bionic-gtk3
     steps:
       - checkout
       - run: >
           echo "deb-src http://us.archive.ubuntu.com/ubuntu/ bionic main"
           | sudo tee -a /etc/apt/sources.list
       - run: >
           echo "deb-src http://us.archive.ubuntu.com/ubuntu/ bionic-updates main"
           | sudo tee -a /etc/apt/sources.list
       - run: cat /etc/apt/sources.list
       - run: ci/circleci-build-debian-gtk3.sh
       - run: ci/circleci-upload.sh
   build-buster:
     docker:
       - image: circleci/buildpack-deps:buster-scm
     environment:
       - OCPN_TARGET:  buster
     steps:
       - checkout
       - run: ci/circleci-build-debian-gtk3.sh
       - run: ci/circleci-upload.sh
   build-flatpak:
     machine:
       image: circleci/classic:201808-01
     environment:
       - OCPN_TARGET:  flatpak
     steps:
       - checkout
       - run: ci/circleci-build-flatpak.sh
       - run: ci/circleci-upload-flatpak.sh
   build-mingw:
     docker:
         - image: fedora:29
     environment:
       - OCPN_TARGET:  mingw
     steps:
       - run: su -c "dnf install -q -y git openssh-clients openssh-server"
       - checkout
       - run: ci/circleci-build-mingw.sh
       - run: ci/circleci-upload.sh
   build-macos:
     macos:
       xcode: "11.0.0"
     environment:
       - OCPN_TARGET:  macos
     steps:
       - checkout
       - run: ci/circleci-build-macos.sh
       - run: ci/circleci-upload.sh
   build-android-arm64:
     docker:
       - image: circleci/android:api-28-ndk 
     environment:
       - OCPN_TARGET:  android-arm64
     steps:
       - checkout
       - run: ci/circleci-build-android-arm64.sh
       - run: ci/circleci-upload.sh
   build-android-armhf:
     docker:
       - image: circleci/android:api-28-ndk 
     environment:
       - OCPN_TARGET:  android-armhf
     steps:
       - checkout
       - run: ci/circleci-build-android-armhf.sh
       - run: ci/circleci-upload.sh
   build-armhf-stretch:
      machine: true
      environment:
        - OCPN_TARGET=stretch-armhf
        - DOCKER_IMAGE=jongough/raspbian-stretch:latest
        - BUILD_FLAGS=-j3
        - BUILD_ENV=raspbian
      steps:
        - checkout
        - run: chmod a+x ./ci/*.sh
        - run:
            command: ci/circleci-build-raspbian-armhf.sh
            no_output_timeout: 30m
        - run: ci/circleci-upload_arm.sh
   build-armhf-buster:
      machine: true
      environment:
        - OCPN_TARGET=buster-armhf
        - DOCKER_IMAGE=jongough/raspbian-buster:plugin_build_tooling_current
        - BUILD_FLAGS=-j3
        - BUILD_ENV=raspbian
      steps:
        - checkout
        - run: chmod a+x ./ci/*.sh
        - run:
            command: ci/circleci-build-raspbian-armhf.sh
            no_output_timeout: 30m
        - run: ci/circleci-upload_arm.sh
   build-armhf-bionic-64:
      machine:
       image: ubuntu-1804:202010-01
      environment:
        - OCPN_TARGET=bionic-arm64
        - OCPN_BRANCH=master
        - DOCKER_IMAGE=arm64v8/ubuntu:18.04
        - BUILD_FLAGS=-j3
        - BUILD_ENV=ubuntu
      steps:
        - checkout
        - run: chmod a+x ./ci/*.sh
        - run:
            command: ci/circleci-build-raspbian-armhf.sh
            no_output_timeout: 30m
        - run: ci/circleci-upload_arm.sh
workflows:
  version: 2
  build_all:
    jobs:
      - build-trusty:
          filters:
            branches:
              only: master
      - build-xenial:
          filters:
            branches:
              only: master
      - build-bionic-gtk3:
          filters:
            branches:
              only: master
      - build-bionic:
          filters:
            branches:
              only: master
      - build-focal:
          filters:
            branches:
              only: master
      - build-buster:
          filters:
            branches:
              only: master
      - build-flatpak:
          filters:
            branches:
              only: master
      - build-macos:
          filters:
            branches:
              only: master
      - build-mingw:
          filters:
            branches:
              only: master
      - build-android-arm64:
          filters:
            branches:
              only: master
      - build-android-armhf:
          filters:
            branches:
              only: master
      - build-armhf-stretch:
          filters:
            branches:
              only: master
      - build-armhf-buster:
          filters:
            branches:
              only: master
      - build-armhf-bionic-64:
          filters:
            branches:
              only: master
